### ISSUE TITLE
gVim on Windows  reporting Pattern not found when starting

### ISSUE THREAD

**Issue by FilBot3** [petobens/poet-v#14]
I have gVim 8.2 running on Windows 10. I have `poetry` installed and am able to run it from the terminal within Vim and also from Cmder. I then have the plugin cloned into the following folder

* `$env:HOME\vimfiles\pack\vendor\start\peot-v`

I can start up gVim and see from running `:scriptnames` that it's loading. I then put in `$MYVIMRC` the following snippet to have it automatically load the virtualenv so pylint stops complaining that it can't find diagrams in the load path

```vimscript
" poet-v
try
  g:poetv_auto_activate = 1
endtry
```

However, when I start gVim, it says that: `Pattern not found: poetv_auto_activate = 1`.

![2020-08-28 19_05_47-Window](https://user-images.githubusercontent.com/3039509/91623743-49a77700-e962-11ea-9a3b-c2294fdbfadb.png)

The same thing happens when using command-line vim.

Poetry Version

```powershell
> poetry --version
Poetry version 1.0.10
```

**Comment by petobens** [comment]
I don't use windows or gvim but can you try writing the setting as `let g:poetv_auto_activate = 1` instead? (note the `let` which is used by vim to define variables).

**Comment by FilBot3** [comment]
Duh. I totally forgot I needed to put the `let` in there.  That did the trick. Thank you.
