### ISSUE TITLE
Error: pipenv executable not found

### ISSUE THREAD

**Issue by amitkot** [petobens/poet-v#17]
I use poetry and do not have pipenv installed.

Tried adding this plugin - I use NeoVim 0.7 on macOS - I can be more specific if needed.

I use packer and installed by adding:
```
  use "petobens/poet-v"
```

When opening neovim I now get this error message:
```
Error detected while processing /Users/xxxx/.local/share/nvim/site/pack/packer/start/poet-v/plugin/poetv.vim:                                                                   
line   19:                                                                                                                                                                      
pipenv executable not found.
```

**Comment by alac1984** [comment]
I'm facing the same problem. I use Vundle to manage my plugins. I tried to exclude pipenv from `g:poetv_executables`, but the error persists.

**Comment by MRocholl** [comment]
Same here.

**Comment by pfassina** [comment]
Same here

**Comment by slacksystem** [comment]
I had this too. I submitted #19 to fix it. Hopefully that gets merged soon
