### ISSUE TITLE
Status Line symbol

### ISSUE THREAD

**Issue by Tyrn** [petobens/poet-v#21]
I'm so sorry,

Where does the `poetv_statusline_symbol` show? The plugin works (`$ where python` after `:PoetvActivate` shows exactly what I expect), but no visual trace in the status line. Curiously, the zsh console looks just like the system one, minus (venv).

BTW, I can't see the statusline symbol on your screenshot.

**Comment by gokomer** [comment]
I'm having the same issue.

**Comment by petobens** [comment]
If you use aerial it should be shown next to venv name. See the small terminal icon to the left of `20%` in the README screenshot.

**Comment by gokomer** [comment]
This is how I installed both poet-v and airline.  No config, just default settings.
```
use "petobens/poet-v"
use "vim-airline/vim-airline"
```

This is how it looks like after `:PoetvActivate`

![image](https://github.com/petobens/poet-v/assets/11593018/f297a69d-8dd6-4629-8157-778983503558)


Is there a config I should do in airline?

**Comment by petobens** [comment]
You might need `let g:airline#extensions#poetv#enabled = 1`?

**Comment by gokomer** [comment]
Now I get the  `Python3 is needed for poet-v to work.` even tough poetry shell is active in the shell I call `nvim .`.

**Comment by petobens** [comment]
You probably need to add something like `let g:python3_host_prog = '/usr/bin/python'`

**Comment by gokomer** [comment]
Error is gone but still no status line. this is `:AirlineExtensions` output `poetv           0       loaded`

![image](https://github.com/petobens/poet-v/assets/11593018/5199cd42-ade8-4a18-b95a-39e72cc00142)

**Comment by petobens** [comment]
Did you  try defining some symbol? `let g:poetv_statusline_symbol = ' '`? 

Also try auto activating with `let g:poetv_auto_activate = 1`

**Comment by gokomer** [comment]
auto activate made it shown but no icon. after setting statusline_symbol it is working. Thank you.

**Comment by petobens** [comment]
Great!
